In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import os
import warnings
warnings.simplefilter('ignore')
import seaborn as sns

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Ridge
from yellowbrick.datasets import load_concrete
from yellowbrick.regressor import ResidualsPlot

In [3]:
history_data = pd.read_csv(os.path.join('Stage2_NCAA_2013T02018.csv'))
history_data.head()

,outcome,TeamID,Score,NumOT,FGM,FGA,FGM3,FGA3,FTM,FTA,OR,DR,Ast,TO,Stl,Blk,PF
0,1,1104,70,0,25,52,6,21,14,14,8,19,14,12,8,4,16
1,1,1107,69,0,28,61,7,19,6,7,14,21,13,12,6,2,22
2,1,1114,84,0,28,61,6,17,22,30,11,28,16,14,9,4,19
3,1,1116,73,0,22,51,3,13,26,32,7,16,16,9,9,8,14
4,1,1120,61,0,22,54,3,11,14,21,12,30,10,16,10,3,17

In [4]:
# Assign X (data) and y (target)
X = history_data.drop(["outcome", "TeamID","NumOT"], axis=1)
y = history_data["outcome"]
print(X.shape, y.shape)

(64410, 14) (64410,)

In [5]:
X.head()

   Score  FGM  FGA  FGM3  FGA3  FTM  FTA  OR  DR  Ast  TO  Stl  Blk  PF
0     70   25   52     6    21   14   14   8  19   14  12    8    4  16
1     69   28   61     7    19    6    7  14  21   13  12    6    2  22
2     84   28   61     6    17   22   30  11  28   16  14    9    4  19
3     73   22   51     3    13   26   32   7  16   16   9    9    8  14
4     61   22   54     3    11   14   21  12  30   10  16   10    3  17

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, stratify=y)

In [7]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [15]:
model = Sequential()
model.add(Dense(units=36, activation='relu', input_dim=14))
model.add(Dense(units=36, activation='relu'))
model.add(Dense(units=2, activation='softmax'))

In [16]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [17]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_3 (Dense)              (None, 36)                540
_________________________________________________________________
dense_4 (Dense)              (None, 36)                1332
_________________________________________________________________
dense_5 (Dense)              (None, 2)                 74
=================================================================
Total params: 1,946
Trainable params: 1,946
Non-trainable params: 0
_________________________________________________________________

In [18]:
from sklearn.preprocessing import StandardScaler
X_scaler = StandardScaler().fit(X_train)

In [19]:
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [20]:
 model.fit(
    X_train_scaled,
    y_train,
    epochs=60,
    shuffle=True,
    verbose=2
)

Train on 48307 samples
Epoch 1/60
48307/48307 - 3s - loss: 0.3070 - accuracy: 0.8644
Epoch 2/60
48307/48307 - 2s - loss: 0.2769 - accuracy: 0.8809
Epoch 3/60
48307/48307 - 3s - loss: 0.2749 - accuracy: 0.8812
Epoch 4/60
48307/48307 - 3s - loss: 0.2737 - accuracy: 0.8818
Epoch 5/60
48307/48307 - 2s - loss: 0.2727 - accuracy: 0.8819
Epoch 6/60
48307/48307 - 3s - loss: 0.2717 - accuracy: 0.8831
Epoch 7/60
48307/48307 - 3s - loss: 0.2710 - accuracy: 0.8831
Epoch 8/60
48307/48307 - 2s - loss: 0.2707 - accuracy: 0.8836
Epoch 9/60
48307/48307 - 3s - loss: 0.2700 - accuracy: 0.8841
Epoch 10/60
48307/48307 - 3s - loss: 0.2694 - accuracy: 0.8835
Epoch 11/60
48307/48307 - 3s - loss: 0.2689 - accuracy: 0.8840
Epoch 12/60
48307/48307 - 3s - loss: 0.2684 - accuracy: 0.8845
Epoch 13/60
48307/48307 - 2s - loss: 0.2682 - accuracy: 0.8853
Epoch 14/60
48307/48307 - 2s - loss: 0.2672 - accuracy: 0.8849
Epoch 15/60
48307/48307 - 2s - loss: 0.2671 - accuracy: 0.8855
Epoch 16/60
48307/48307 - 2s - loss: 0.2661 - accuracy: 0.8850
Epoch 17/60
48307/48307 - 3s - loss: 0.2661 - accuracy: 0.8860
Epoch 18/60
48307/48307 - 3s - loss: 0.2656 - accuracy: 0.8846
Epoch 19/60
48307/48307 - 2s - loss: 0.2653 - accuracy: 0.8862
Epoch 20/60
48307/48307 - 2s - loss: 0.2649 - accuracy: 0.8863
Epoch 21/60
48307/48307 - 2s - loss: 0.2646 - accuracy: 0.8867
Epoch 22/60
48307/48307 - 2s - loss: 0.2640 - accuracy: 0.8865
Epoch 23/60
48307/48307 - 2s - loss: 0.2642 - accuracy: 0.8862
Epoch 24/60
48307/48307 - 2s - loss: 0.2631 - accuracy: 0.8872
Epoch 25/60
48307/48307 - 2s - loss: 0.2630 - accuracy: 0.8869
Epoch 26/60
48307/48307 - 2s - loss: 0.2627 - accuracy: 0.8861
Epoch 27/60
48307/48307 - 2s - loss: 0.2623 - accuracy: 0.8872
Epoch 28/60
48307/48307 - 2s - loss: 0.2620 - accuracy: 0.8866
Epoch 29/60
48307/48307 - 2s - loss: 0.2618 - accuracy: 0.8874
Epoch 30/60
48307/48307 - 2s - loss: 0.2617 - accuracy: 0.8882
Epoch 31/60
48307/48307 - 2s - loss: 0.2605 - accuracy: 0.8880
Epoch 32/60
48307/48307 - 2s - loss: 0.2609 - accuracy: 0.8877
Epoch 33/60
48307/48307 - 2s - loss: 0.2609 - accuracy: 0.8885
Epoch 34/60
48307/48307 - 2s - loss: 0.2604 - accuracy: 0.8880
Epoch 35/60
48307/48307 - 2s - loss: 0.2601 - accuracy: 0.8875
Epoch 36/60
48307/48307 - 2s - loss: 0.2599 - accuracy: 0.8876
Epoch 37/60
48307/48307 - 2s - loss: 0.2595 - accuracy: 0.8876
Epoch 38/60
48307/48307 - 2s - loss: 0.2597 - accuracy: 0.8887
Epoch 39/60
48307/48307 - 2s - loss: 0.2594 - accuracy: 0.8885
Epoch 40/60
48307/48307 - 2s - loss: 0.2587 - accuracy: 0.8890
Epoch 41/60
48307/48307 - 2s - loss: 0.2592 - accuracy: 0.8889
Epoch 42/60
48307/48307 - 2s - loss: 0.2588 - accuracy: 0.8896
Epoch 43/60
48307/48307 - 2s - loss: 0.2587 - accuracy: 0.8888
Epoch 44/60
48307/48307 - 2s - loss: 0.2584 - accuracy: 0.8892
Epoch 45/60
48307/48307 - 2s - loss: 0.2582 - accuracy: 0.8891
Epoch 46/60
48307/48307 - 2s - loss: 0.2574 - accuracy: 0.8896
Epoch 47/60
48307/48307 - 2s - loss: 0.2579 - accuracy: 0.8892
Epoch 48/60
48307/48307 - 2s - loss: 0.2578 - accuracy: 0.8894
Epoch 49/60
48307/48307 - 2s - loss: 0.2569 - accuracy: 0.8894
Epoch 50/60
48307/48307 - 2s - loss: 0.2568 - accuracy: 0.8905
Epoch 51/60
48307/48307 - 2s - loss: 0.2569 - accuracy: 0.8903
Epoch 52/60
48307/48307 - 2s - loss: 0.2565 - accuracy: 0.8898
Epoch 53/60
48307/48307 - 2s - loss: 0.2568 - accuracy: 0.8893
Epoch 54/60
48307/48307 - 2s - loss: 0.2565 - accuracy: 0.8903
Epoch 55/60
48307/48307 - 2s - loss: 0.2560 - accuracy: 0.8900
Epoch 56/60
48307/48307 - 2s - loss: 0.2560 - accuracy: 0.8899
Epoch 57/60
48307/48307 - 2s - loss: 0.2557 - accuracy: 0.8900
Epoch 58/60
48307/48307 - 2s - loss: 0.2559 - accuracy: 0.8896
Epoch 59/60
48307/48307 - 3s - loss: 0.2548 - accuracy: 0.8912
Epoch 60/60
48307/48307 - 2s - loss: 0.2551 - accuracy: 0.8896

In [25]:
deep_model = Sequential()
deep_model.add(Dense(units=6, activation='relu', input_dim=14))
deep_model.add(Dense(units=6, activation='relu'))
deep_model.add(Dense(units=2, activation='softmax'))

In [26]:
deep_model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_9 (Dense)              (None, 6)                 90
_________________________________________________________________
dense_10 (Dense)             (None, 6)                 42
_________________________________________________________________
dense_11 (Dense)             (None, 2)                 14
=================================================================
Total params: 146
Trainable params: 146
Non-trainable params: 0
_________________________________________________________________

In [27]:
deep_model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [28]:
deep_model.fit(
    X_train_scaled,
    y_train,
    epochs=60,
    shuffle=True,
    verbose=2
)

Train on 48307 samples
Epoch 1/60
48307/48307 - 3s - loss: 0.3878 - accuracy: 0.8219
Epoch 2/60
48307/48307 - 3s - loss: 0.2856 - accuracy: 0.8786
Epoch 3/60
48307/48307 - 2s - loss: 0.2782 - accuracy: 0.8809
Epoch 4/60
48307/48307 - 2s - loss: 0.2754 - accuracy: 0.8812
Epoch 5/60
48307/48307 - 2s - loss: 0.2744 - accuracy: 0.8815
Epoch 6/60
48307/48307 - 2s - loss: 0.2737 - accuracy: 0.8811
Epoch 7/60
48307/48307 - 2s - loss: 0.2733 - accuracy: 0.8821
Epoch 8/60
48307/48307 - 2s - loss: 0.2729 - accuracy: 0.8825
Epoch 9/60
48307/48307 - 2s - loss: 0.2725 - accuracy: 0.8821
Epoch 10/60
48307/48307 - 2s - loss: 0.2725 - accuracy: 0.8822
Epoch 11/60
48307/48307 - 2s - loss: 0.2725 - accuracy: 0.8818
Epoch 12/60
48307/48307 - 2s - loss: 0.2721 - accuracy: 0.8820
Epoch 13/60
48307/48307 - 2s - loss: 0.2723 - accuracy: 0.8818
Epoch 14/60
48307/48307 - 2s - loss: 0.2723 - accuracy: 0.8819
Epoch 15/60
48307/48307 - 2s - loss: 0.2720 - accuracy: 0.8819
Epoch 16/60
48307/48307 - 2s - loss: 0.2721 - accuracy: 0.8820
Epoch 17/60
48307/48307 - 2s - loss: 0.2719 - accuracy: 0.8824
Epoch 18/60
48307/48307 - 2s - loss: 0.2722 - accuracy: 0.8823
Epoch 19/60
48307/48307 - 2s - loss: 0.2721 - accuracy: 0.8818
Epoch 20/60
48307/48307 - 2s - loss: 0.2724 - accuracy: 0.8822
Epoch 21/60
48307/48307 - 2s - loss: 0.2721 - accuracy: 0.8817
Epoch 22/60
48307/48307 - 2s - loss: 0.2721 - accuracy: 0.8818
Epoch 23/60
48307/48307 - 3s - loss: 0.2720 - accuracy: 0.8824
Epoch 24/60
48307/48307 - 2s - loss: 0.2720 - accuracy: 0.8822
Epoch 25/60
48307/48307 - 3s - loss: 0.2719 - accuracy: 0.8814
Epoch 26/60
48307/48307 - 3s - loss: 0.2719 - accuracy: 0.8820
Epoch 27/60
48307/48307 - 3s - loss: 0.2718 - accuracy: 0.8820
Epoch 28/60
48307/48307 - 3s - loss: 0.2718 - accuracy: 0.8819
Epoch 29/60
48307/48307 - 3s - loss: 0.2720 - accuracy: 0.8819
Epoch 30/60
48307/48307 - 3s - loss: 0.2718 - accuracy: 0.8824
Epoch 31/60
48307/48307 - 3s - loss: 0.2718 - accuracy: 0.8819
Epoch 32/60
48307/48307 - 2s - loss: 0.2717 - accuracy: 0.8824
Epoch 33/60
48307/48307 - 3s - loss: 0.2719 - accuracy: 0.8819
Epoch 34/60
48307/48307 - 2s - loss: 0.2717 - accuracy: 0.8825
Epoch 35/60
48307/48307 - 2s - loss: 0.2718 - accuracy: 0.8822
Epoch 36/60
48307/48307 - 2s - loss: 0.2718 - accuracy: 0.8822
Epoch 37/60
48307/48307 - 2s - loss: 0.2716 - accuracy: 0.8821
Epoch 38/60
48307/48307 - 2s - loss: 0.2717 - accuracy: 0.8826
Epoch 39/60
48307/48307 - 2s - loss: 0.2716 - accuracy: 0.8815
Epoch 40/60
48307/48307 - 2s - loss: 0.2717 - accuracy: 0.8825
Epoch 41/60
48307/48307 - 2s - loss: 0.2718 - accuracy: 0.8825
Epoch 42/60
48307/48307 - 2s - loss: 0.2716 - accuracy: 0.8828
Epoch 43/60
48307/48307 - 2s - loss: 0.2714 - accuracy: 0.8823
Epoch 44/60
48307/48307 - 2s - loss: 0.2716 - accuracy: 0.8821
Epoch 45/60
48307/48307 - 2s - loss: 0.2714 - accuracy: 0.8818
Epoch 46/60
48307/48307 - 2s - loss: 0.2717 - accuracy: 0.8829
Epoch 47/60
48307/48307 - 2s - loss: 0.2712 - accuracy: 0.8826
Epoch 48/60
48307/48307 - 2s - loss: 0.2715 - accuracy: 0.8825
Epoch 49/60
48307/48307 - 2s - loss: 0.2714 - accuracy: 0.8825
Epoch 50/60
48307/48307 - 2s - loss: 0.2716 - accuracy: 0.8821
Epoch 51/60
48307/48307 - 2s - loss: 0.2714 - accuracy: 0.8829
Epoch 52/60
48307/48307 - 2s - loss: 0.2712 - accuracy: 0.8827
Epoch 53/60
48307/48307 - 2s - loss: 0.2714 - accuracy: 0.8817
Epoch 54/60
48307/48307 - 2s - loss: 0.2715 - accuracy: 0.8823
Epoch 55/60
48307/48307 - 2s - loss: 0.2712 - accuracy: 0.8821
Epoch 56/60
48307/48307 - 2s - loss: 0.2712 - accuracy: 0.8825
Epoch 57/60
48307/48307 - 2s - loss: 0.2714 - accuracy: 0.8825
Epoch 58/60
48307/48307 - 2s - loss: 0.2712 - accuracy: 0.8813
Epoch 59/60
48307/48307 - 2s - loss: 0.2713 - accuracy: 0.8818
Epoch 60/60
48307/48307 - 2s - loss: 0.2713 - accuracy: 0.8820

In [29]:
model_loss, model_accuracy = model.evaluate(
    X_test_scaled, y_test, verbose=2)
print(
    f"Normal Neural Network - Loss: {model_loss}, Accuracy: {model_accuracy}")

16103/16103 - 1s - loss: 0.2832 - accuracy: 0.8764
Normal Neural Network - Loss: 0.2832301271403716, Accuracy: 0.8764205574989319

In [30]:
model_loss, model_accuracy = deep_model.evaluate(
    X_test_scaled, y_test, verbose=2)
print(f"Deep Neural Network - Loss: {model_loss}, Accuracy: {model_accuracy}")

16103/16103 - 1s - loss: 0.2684 - accuracy: 0.8833
Deep Neural Network - Loss: 0.26841989941888067, Accuracy: 0.8832515478134155

In [31]:
Edeep_model = Sequential()
Edeep_model.add(Dense(units=6, activation='relu', input_dim=14))
Edeep_model.add(Dense(units=6, activation='relu'))
Edeep_model.add(Dense(units=6, activation='relu'))
Edeep_model.add(Dense(units=2, activation='softmax'))

In [32]:
Edeep_model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_12 (Dense)             (None, 6)                 90
_________________________________________________________________
dense_13 (Dense)             (None, 6)                 42
_________________________________________________________________
dense_14 (Dense)             (None, 6)                 42
_________________________________________________________________
dense_15 (Dense)             (None, 2)                 14
=================================================================
Total params: 188
Trainable params: 188
Non-trainable params: 0
_________________________________________________________________

In [33]:
Edeep_model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [34]:
Edeep_model.fit(
    X_train_scaled,
    y_train,
    epochs=60,
    shuffle=True,
    verbose=2
)

Train on 48307 samples
Epoch 1/60
48307/48307 - 3s - loss: 0.3674 - accuracy: 0.8339
Epoch 2/60
48307/48307 - 3s - loss: 0.2809 - accuracy: 0.8805
Epoch 3/60
48307/48307 - 2s - loss: 0.2770 - accuracy: 0.8807
Epoch 4/60
48307/48307 - 2s - loss: 0.2757 - accuracy: 0.8818
Epoch 5/60
48307/48307 - 3s - loss: 0.2753 - accuracy: 0.8817
Epoch 6/60
48307/48307 - 2s - loss: 0.2750 - accuracy: 0.8815
Epoch 7/60
48307/48307 - 2s - loss: 0.2742 - accuracy: 0.8813
Epoch 8/60
48307/48307 - 2s - loss: 0.2740 - accuracy: 0.8811
Epoch 9/60
48307/48307 - 2s - loss: 0.2738 - accuracy: 0.8819
Epoch 10/60
48307/48307 - 2s - loss: 0.2738 - accuracy: 0.8819
Epoch 11/60
48307/48307 - 2s - loss: 0.2734 - accuracy: 0.8817
Epoch 12/60
48307/48307 - 2s - loss: 0.2733 - accuracy: 0.8812
Epoch 13/60
48307/48307 - 2s - loss: 0.2733 - accuracy: 0.8818
Epoch 14/60
48307/48307 - 2s - loss: 0.2731 - accuracy: 0.8823
Epoch 15/60
48307/48307 - 2s - loss: 0.2730 - accuracy: 0.8819
Epoch 16/60
48307/48307 - 2s - loss: 0.2727 - accuracy: 0.8818
Epoch 17/60
48307/48307 - 2s - loss: 0.2730 - accuracy: 0.8825
Epoch 18/60
48307/48307 - 2s - loss: 0.2726 - accuracy: 0.8823
Epoch 19/60
48307/48307 - 2s - loss: 0.2729 - accuracy: 0.8818
Epoch 20/60
48307/48307 - 3s - loss: 0.2727 - accuracy: 0.8815
Epoch 21/60
48307/48307 - 2s - loss: 0.2724 - accuracy: 0.8824
Epoch 22/60
48307/48307 - 2s - loss: 0.2726 - accuracy: 0.8821
Epoch 23/60
48307/48307 - 3s - loss: 0.2723 - accuracy: 0.8821
Epoch 24/60
48307/48307 - 2s - loss: 0.2724 - accuracy: 0.8820
Epoch 25/60
48307/48307 - 2s - loss: 0.2722 - accuracy: 0.8821
Epoch 26/60
48307/48307 - 2s - loss: 0.2721 - accuracy: 0.8821
Epoch 27/60
48307/48307 - 2s - loss: 0.2722 - accuracy: 0.8816
Epoch 28/60
48307/48307 - 2s - loss: 0.2722 - accuracy: 0.8826
Epoch 29/60
48307/48307 - 2s - loss: 0.2721 - accuracy: 0.8827
Epoch 30/60
48307/48307 - 2s - loss: 0.2720 - accuracy: 0.8820
Epoch 31/60
48307/48307 - 2s - loss: 0.2717 - accuracy: 0.8825
Epoch 32/60
48307/48307 - 2s - loss: 0.2718 - accuracy: 0.8820
Epoch 33/60
48307/48307 - 2s - loss: 0.2719 - accuracy: 0.8819
Epoch 34/60
48307/48307 - 2s - loss: 0.2720 - accuracy: 0.8824
Epoch 35/60
48307/48307 - 2s - loss: 0.2721 - accuracy: 0.8817
Epoch 36/60
48307/48307 - 2s - loss: 0.2716 - accuracy: 0.8831
Epoch 37/60
48307/48307 - 2s - loss: 0.2720 - accuracy: 0.8824
Epoch 38/60
48307/48307 - 2s - loss: 0.2719 - accuracy: 0.8827
Epoch 39/60
48307/48307 - 2s - loss: 0.2716 - accuracy: 0.8829
Epoch 40/60
48307/48307 - 2s - loss: 0.2715 - accuracy: 0.8821
Epoch 41/60
48307/48307 - 2s - loss: 0.2716 - accuracy: 0.8821
Epoch 42/60
48307/48307 - 2s - loss: 0.2717 - accuracy: 0.8825
Epoch 43/60
48307/48307 - 2s - loss: 0.2716 - accuracy: 0.8823
Epoch 44/60
48307/48307 - 2s - loss: 0.2718 - accuracy: 0.8821
Epoch 45/60
48307/48307 - 2s - loss: 0.2715 - accuracy: 0.8815
Epoch 46/60
48307/48307 - 2s - loss: 0.2716 - accuracy: 0.8825
Epoch 47/60
48307/48307 - 3s - loss: 0.2716 - accuracy: 0.8826
Epoch 48/60
48307/48307 - 2s - loss: 0.2716 - accuracy: 0.8825
Epoch 49/60
48307/48307 - 3s - loss: 0.2716 - accuracy: 0.8817
Epoch 50/60
48307/48307 - 3s - loss: 0.2715 - accuracy: 0.8826
Epoch 51/60
48307/48307 - 5s - loss: 0.2714 - accuracy: 0.8824
Epoch 52/60
48307/48307 - 6s - loss: 0.2716 - accuracy: 0.8815
Epoch 53/60
48307/48307 - 5s - loss: 0.2716 - accuracy: 0.8821
Epoch 54/60
48307/48307 - 4s - loss: 0.2715 - accuracy: 0.8827
Epoch 55/60
48307/48307 - 4s - loss: 0.2716 - accuracy: 0.8821
Epoch 56/60
48307/48307 - 2s - loss: 0.2715 - accuracy: 0.8825
Epoch 57/60
48307/48307 - 2s - loss: 0.2714 - accuracy: 0.8831
Epoch 58/60
48307/48307 - 2s - loss: 0.2714 - accuracy: 0.8831
Epoch 59/60
48307/48307 - 2s - loss: 0.2716 - accuracy: 0.8828
Epoch 60/60
48307/48307 - 2s - loss: 0.2713 - accuracy: 0.8827

In [35]:
model_loss, model_accuracy = Edeep_model.evaluate(
    X_test_scaled, y_test, verbose=2)
print(
    f"Normal Neural Network - Loss: {model_loss}, Accuracy: {model_accuracy}")

16103/16103 - 1s - loss: 0.2714 - accuracy: 0.8853
Normal Neural Network - Loss: 0.27140805092293496, Accuracy: 0.885300874710083

In [36]:
from sklearn.metrics import classification_report

In [37]:
encoded_predictions = Edeep_model.predict_classes(X_test_scaled)
encoded_predictions

array([1, 0, 1, ..., 1, 0, 1])

In [38]:
target_names = ['Loss', 'Won']

In [39]:
print(classification_report(y_test, encoded_predictions, target_names=target_names))

              precision    recall  f1-score   support

        Loss       0.87      0.91      0.89      8052
         Won       0.91      0.86      0.88      8051

    accuracy                           0.89     16103
   macro avg       0.89      0.89      0.89     16103
weighted avg       0.89      0.89      0.89     16103

In [40]:
test = pd.read_csv(os.path.join('2019.csv'))
test.head()

,outcome,TeamID,Score,NumOT,FGM,FGA,FGM3,FGA3,FTM,FTA,OR,DR,Ast,TO,Stl,Blk,PF
0,1,1104,82,0,27,55,9,24,19,28,16,29,17,20,3,6,24
1,1,1113,102,0,33,78,10,26,26,44,20,38,11,17,3,2,26
2,1,1119,73,0,22,51,9,30,20,29,6,22,14,6,5,1,22
3,1,1120,101,0,38,74,18,38,7,14,19,23,24,13,9,8,21
4,1,1123,86,0,32,65,7,19,15,20,16,26,14,9,7,5,18

In [41]:
test.isnull().sum()

outcome    0
TeamID     0
Score      0
NumOT      0
FGM        0
FGA        0
FGM3       0
FGA3       0
FTM        0
FTA        0
OR         0
DR         0
Ast        0
TO         0
Stl        0
Blk        0
PF         0
dtype: int64

In [44]:
# X = test.drop(["outcome", "wpf"], axis=1)
X = test.drop(["outcome", "TeamID","NumOT"], axis=1)
y = test["outcome"]
print(X.shape, y.shape)

(10926, 14) (10926,)

In [45]:
#To predict outcome for 2019 dataset
encoded_predictions2 = deep_model.predict_classes(X)
encoded_predictions2

array([1, 1, 1, ..., 1, 0, 1])

In [46]:
print(classification_report(y, encoded_predictions2, target_names=target_names))

              precision    recall  f1-score   support

        Loss       0.95      0.50      0.66      5463
         Won       0.66      0.97      0.79      5463

    accuracy                           0.74     10926
   macro avg       0.81      0.74      0.72     10926
weighted avg       0.81      0.74      0.72     10926

In [57]:
from sklearn.metrics import confusion_matrix

log_cfm = confusion_matrix(y, encoded_predictions2)
print("Confusion matrix:")
print(log_cfm, end='\n\n')
print('-'*15)
print(np.array([['TN', 'FP'],[ 'FN' , 'TP']]))

Confusion matrix:
[[2731 2732]
 [ 142 5321]]

---------------

NameError: name 'np' is not defined

In [47]:
pd.DataFrame({"Prediction": encoded_predictions2, "Actual": y}).reset_index(drop=True)

       Prediction  Actual
0               1       1
1               1       1
2               1       1
3               1       1
4               1       1
5               1       1
6               1       1
7               1       1
8               1       1
9               1       1
10              1       1
11              1       1
12              1       1
13              1       1
14              1       1
15              1       1
16              1       1
17              1       1
18              1       1
19              1       1
20              1       1
21              1       1
22              1       1
23              1       1
24              1       1
25              1       1
26              1       1
27              1       1
28              1       1
29              1       1
...           ...     ...
10896           0       0
10897           1       0
10898           0       0
10899           0       0
10900           1       0
10901           0       0
10902           0       0
10903           0       0
10904           0       0
10905           1       0
10906           0       0
10907           0       0
10908           1       0
10909           0       0
10910           1       0
10911           0       0
10912           0       0
10913           1       0
10914           1       0
10915           0       0
10916           0       0
10917           0       0
10918           0       0
10919           1       0
10920           1       0
10921           0       0
10922           0       0
10923           1       0
10924           0       0
10925           1       0

[10926 rows x 2 columns]

In [48]:
temp_df = pd.DataFrame()

In [49]:
temp_df['prediction'] = encoded_predictions2
temp_df['actual'] = y.tolist()

In [50]:
#temp_df["TeamID"]=X["TeamID"].tolist()

In [51]:
output_File = "predictions_NN_2019-noTeamID.csv"

In [52]:
temp_df.to_csv(output_File,index=False)

In [53]:
model_loss, model_accuracy = deep_model.evaluate(
    X, y, verbose=2)
print(
    f"Normal Neural Network - Loss: {model_loss}, Accuracy: {model_accuracy}")

10926/10926 - 0s - loss: 1.7438 - accuracy: 0.7370
Normal Neural Network - Loss: 1.7438424374228767, Accuracy: 0.7369577288627625